server:
  port: 8082

spring:
  application:
    name: todo-proxy-service

eureka:
  instance:
    instance-id: todo-proxy-service
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
